<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{de8106da-848b-45a1-9ce3-abd3cf68b67b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbServer : FB_Server(VAR_OCPP.stServerParam);

	fbStation01 : FB_Station('ChargingStation01', '2f20aa42275837973ed8f3726bb2709e0a9e476da9c42da38ac113de818d0dbf', fbServer); // ChargingStation01:abcdef
	fbStation02 : FB_Station('ChargingStation02', '5c55b2828abee6bb262ed0505d53d0baa947e050825ef00e7d3432b722177480', fbServer); // ChargingStation02:abcdef
	//fbStation03 : FB_Station('ChargingStation03', 'f207afc2a29d076265649b050ff3f6449b03dc6d04620e269a17cb31584a4471', fbServer); // ChargingStation03:abcdef
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbStation01.Execute();
fbStation02.Execute();
fbServer.Execute();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>